### ISSUE TITLE
Help with Wiki?

### ISSUE THREAD

**Issue by tharun143** [amfoss/Wiki#1]
If this issue was opened for writing a wiki page for amfoss then I would like to propose a work that I have done in Foss.  [Resource](https://tharunravuri2000.gitbook.io/amfoss/#amfoss). If there is any way this resource can help u can use it else you can close this issue 👍

**Comment by vchrombie** [comment]
Thanks for opening the issue @tharun143. We will look into and consider if it is useful.
Thanks for your previous effort in creating this resource. 

Closing this right now, feel free to open if needed. :slightly_smiling_face:
